# Generated by Django 3.1.4 on 2020-12-30 15:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_user_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.user_image_file_path),
        ),
    ]
